### ISSUE TITLE
About the pretrained models

### ISSUE THREAD

**Issue by Tokymin** [XGGNet/Endora#3]
你好，我在加载预训练权重时发现好像和模型是不匹配的，问题如下：
（1）
![图片](https://github.com/XGGNet/Endora/assets/32712253/ae7d8bb6-dfaf-42c6-a373-0bf12b289116)
有一个多出的cov.weight;
（2）RuntimeError: Error(s) in loading state_dict for OptimizedModule:size mismatch for _orig_mod.pos_embed: copying a param with shape torch.Size([1, 64, 1152]) from checkpoint, the shape in l current model is torch.Size([1, 16, 1152]).

请问我需要改动模型代码哪里的参数吗？希望能得到您的解答！谢谢！！！

**Comment by LiuHengyu321** [comment]
Hi @Tokymin,

May I ask which checkpoint you use to load?

**Comment by Tokymin** [comment]
> Hi @Tokymin,
> 
> May I ask which checkpoint you use to load?

@LiuHengyu321 I deeply appreciate your reply, I had abolve problems when I tried the Kvasir-Capsule_0150000.pt and Colonoscopic_0150000.pt checkpoints. But only when I tried the cho dataset，everything seems to be fine.
![图片](https://github.com/XGGNet/Endora/assets/32712253/50125a44-37c8-42d6-a3fd-832bae8d0b6a)

**Comment by LiuHengyu321** [comment]
Hi @Tokymin,

Thank you for your checking!

I have checked the sample.py and find that `model.load_state_dict(state_dict, strict=False)`  should be added when loading the pretrained model. And I have added this to [sample.py](https://github.com/XGGNet/Endora/blob/main/sample/sample.py).

**Comment by Tokymin** [comment]
It works, thank you again!
