### ISSUE TITLE
Size mismatch for pos_embed

### ISSUE THREAD

**Issue by Loping151** [XGGNet/Endora#5]
What I actually run and what had happened:

```bash
(base) root@I1ac8226a6300101da2:~/Endora# python sample/sample.py     --config ./configs/col/col_sample.yaml     --ckpt Colonoscopic_0150000.pt     --save_video_path output
Using Ema!
Traceback (most recent call last):
  File "sample/sample.py", line 139, in <module>
    main(omega_conf)
  File "sample/sample.py", line 64, in main
    model.load_state_dict(state_dict, strict=False)
  File "/usr/local/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for EnDora:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 64, 1152]) from checkpoint, the shape in current model is torch.Size([1, 16, 1152]).
```

The solution in the previous issue: adding `model.load_state_dict(state_dict, strict=False)` in `sample.py` does not work, and I'm using the latest code without modifying it. What can cause the mismatch? Should I change some params?

**Comment by LiuHengyu321** [comment]
Hi @Loping151! Thank you for your interest in our work!

I've just reviewed the config of the Colonoscopic dataset in `configs/col/col_sample.yaml` and noticed that the image size has been incorrectly specified. The pretrained model uses an image size of 128 × 128. 

Thank you for your reminder, and I will update the `configs/col/col_sample.yaml` accordingly.

**Comment by Loping151** [comment]
Thank you. It's OK now.
