### ISSUE TITLE
A question about the magic number 0.18215

### ISSUE THREAD

**Issue by mswwd** [XGGNet/Endora#6]
Thank you for the paper and the accessible code ! However, it's confusing for me that you divide the output of VAE encoder by 0.18215 . Could you please tell me where the magic number comes from?

**Comment by chenxinli001** [comment]
thank you! The scaling of VAE latent is set for the pre-trained VAE. So we just copy the same scaling factor from that of the utilized VAE.

**Comment by mswwd** [comment]
Thanks. I found it in the LDM code.
